import { BaseEntity } from '../../common/base.entity';
import { PictureEntity } from '../picture/picture.entity';
import { CollectionEntity } from '../collection/collection.entity';
import { CommentEntity } from '../comment/comment.entity';
import { PictureUserActivityEntity } from '../picture/user-activity/user-activity.entity';
import { SignupType } from '../../../enum/signupType';
import { Status } from '../../../enum/userStatus';
import { Role } from './enum/role.enum';
import { CredentialsEntity } from '../credentials/credentials.entity';
import { BadgeEntity } from '../badge/badge.entity';
export declare class UserEntity extends BaseEntity {
    readonly id: number;
    readonly username: string;
    role: Role;
    name: string;
    identifier: string;
    verificationToken: string;
    status: Status;
    signupType: SignupType;
    readonly email: string;
    hash: string;
    readonly salt: string;
    avatar: string;
    cover?: string;
    bio: string;
    website: string;
    isOnline: boolean;
    gender: number;
    genderSecret: boolean;
    birthday?: Date;
    birthdayShow: number;
    readonly pictures: PictureEntity[];
    readonly comments: CommentEntity[];
    readonly collections: CollectionEntity[];
    readonly credentials: CredentialsEntity[];
    readonly pictureActivities: PictureUserActivityEntity[];
    badge: BadgeEntity[];
    isEmailVerified: boolean;
    isFollowing: number;
    likedCount: number;
    likesCount: number;
    pictureCount: number;
    followerCount: number;
    followedCount: number;
    isVerified(): boolean;
    isActive(): boolean;
    get fullName(): string;
    get isPassword(): boolean;
}
